#!/bin/bash

alias ls='LC_COLLATE=C ls -A -o -h --color=always --group-directories-first'

alias chx='chmod +x'
alias permof='stat --printf "%a\n"'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'
alias sudo='doas'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec sx'

hs() {
    history -w /dev/stdout | cat - "${HOME}/.bash_history" | awk '!x[$0]++' | grep "${1}"
}

gitpullall() {
    for _dir in */.git
    do
        git -C "$(realpath "${_dir}/..")" pull
    done
}

alias reboot='doas /home/igor/arch/scripts/reboot.sh reboot'
alias poweroff='doas /home/igor/arch/scripts/reboot.sh poweroff'

alias rsnc='doas pacman -Rsnc'
alias work='/home/igor/arch/scripts/work.sh'
alias speedtest='wget http://mirror.carnet.hr/debian-cd/10.10.0/amd64/iso-cd/debian-10.10.0-amd64-netinst.iso -O /dev/null'
alias syu='doas pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
alias mountdisk='doas mount -t ext4 -U 9989d2cc-d8bd-4919-a8ca-2395b60969b8 /home/igor/_disk'
alias mountmmc='doas mount -t ext4 -U ce63484b-3828-4024-9f9c-c120f43ca4ec /home/igor/_mmc'
alias mountazure='/home/igor/arch/scripts/azure.sh'
alias ddiff='code -d'
alias wget='wget --no-hsts'
alias rezije='node /home/igor/git/rezije/main.js'
alias ytdl='youtube-dl --extract-audio --audio-format mp3 '
alias firefox='firefox-socket-control'
alias ncdu='ncdu --color dark'
alias menu='/home/igor/arch/tint2/menu.sh'
alias usb='doas /home/igor/arch/scripts/usb.sh'
alias busy='fuser -Mv'
alias myip='curl ipinfo.io'

alias vboxload='doas modprobe -a vboxdrv vboxnetadp vboxnetflt'

# shellcheck disable=SC1090
_source() {
    [ -f "${1}" ] && source "${1}"
}

_source '/home/igor/arch/scripts/env.sh'
_source '/usr/share/git/completion/git-prompt.sh'
_source '/home/igor/arch/lf/icons.sh'

# _bold="\033[1m"
# _color="\033[32m"
# _gray="\033[37m"
# _reset="\033[0m"

PS1='\w $(__git_ps1 "\[\033[37m\](%s)\[\033[0m\] ")\[\033[32m\]\[\033[1m\]>>\[\033[0m\] '

if [ "$(hostname)" = "alpine" ]
then
    PS1='\w \[\033[34m\]\[\033[1m\]\h >>\[\033[0m\] '
    alias ls='LC_COLLATE=C ls -A -h --color=always --group-directories-first'
fi
