#!/bin/bash

alias ls='LC_COLLATE=C ls -A -l -h --color=always --group-directories-first'

alias chx='chmod +x'
alias permof='stat --printf "%a\n"'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'
alias sudo='doas'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec sx'

hs() {
    history -w /dev/stdout | cat - "${HOME}/.bash_history" | awk '!x[$0]++' | grep "${1}"
}

gitpullall() {
    for _dir in */.git
    do
        git -C "$(realpath "${_dir}/..")" pull
    done
}

alias reboot='doas /home/igor/arch/scripts/reboot.sh reboot'
alias poweroff='doas /home/igor/arch/scripts/reboot.sh poweroff'

alias rsnc='doas pacman -Rsnc'
alias work='/home/igor/arch/scripts/work.sh'
alias speedtest='wget http://mirror.carnet.hr/debian-cd/10.10.0/amd64/iso-cd/debian-10.10.0-amd64-netinst.iso -O /dev/null'
alias syu='doas pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
alias mountdisk='doas mount -t ext4 -U 23147c37-efb6-4837-83aa-87808c70b87a /home/igor/_disk'
alias mountmmc='doas mount -t ext4 -U ce63484b-3828-4024-9f9c-c120f43ca4ec /home/igor/_mmc'
alias mountazure='/home/igor/arch/scripts/azure.sh'
alias ddiff='code -d'
alias wget='wget --no-hsts'
alias rezije='node /home/igor/git/rezije/main.js'
alias ytdl='youtube-dl --extract-audio --audio-format mp3 '
alias firefox='firefox-socket'
alias ncdu='ncdu --color dark'
alias menu='/home/igor/arch/tint2/menu.sh'
alias usb='doas /home/igor/arch/scripts/usb.sh'
alias busy='fuser -Mv'
alias myip='curl ipinfo.io'
alias srcinfo='makepkg --printsrcinfo > .SRCINFO'
alias df2='lfs'

alias vboxload='doas modprobe -a vboxdrv vboxnetadp vboxnetflt'

# shellcheck disable=SC1090
_source() {
    [ -f "${1}" ] && source "${1}"
}

_source '/home/igor/arch/scripts/env.sh'
_source '/usr/share/git/completion/git-prompt.sh'
_source '/home/igor/arch/lf/icons.sh'

_bold="\033[1m"
_green="\033[32m"
_blue="\033[94m"
_gray="\033[37m"
_reset="\033[0m"
PS1="\w \$(__git_ps1 \"\[${_gray}\](%s)\[${_reset}\] \")\[${_green}\]\[${_bold}\]>>\[${_reset}\] "

if [ "$(hostname)" = "avacyn3" ]
then
    PS1="\w \[${_blue}\]\[${_bold}\]avacyn3 >>\[${_reset}\] "
    alias ls='LC_COLLATE=C ls -A -l -h --color=always --group-directories-first'
fi