#!/bin/bash

alias ls='LC_COLLATE=C ls -A -l -h -N --color=always --group-directories-first --time-style="+[%Y-%m-%dT%H:%M:%S]"'
alias chx='chmod +x'
#alias permof='/home/igor/arch/scripts/permof.sh'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'
alias sudo='doas'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec /usr/bin/sx'
alias sx='exec /usr/bin/sx'

hs() {
    { cat "/home/igor/.bash_history"; history | sed 's/^[ \t]*[0-9]\+[ \t]*//'; } | awk '!x[$0]++' | grep -i "${1}"
}

gitpullall() {
    for _dir in */.git
    do
        printf 'Pulling \033[94m%s\033[0m\n' "${_dir%%/*}"
        git -C "$(realpath "${_dir}/..")" pull
    done
}

alias reboot='doas /home/igor/arch/scripts/power.sh reboot'
alias poweroff='doas /home/igor/arch/scripts/power.sh poweroff'
alias suspend='doas /home/igor/arch/scripts/suspend.sh'

alias rsnc='doas pacman -Rsnc'
alias work='/home/igor/arch/scripts/work.sh'
alias speedtest='wget https://avacyn.radiance.hr/stuff/debian-12.5.0-amd64-netinst.iso -O /dev/null'
alias syu='doas pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
alias wifi='doas /home/igor/arch/scripts/wifi.sh'

alias mountall='doas /home/igor/arch/scripts/mount.sh all'
alias mountsmb='doas /home/igor/arch/scripts/mount.sh smb'
alias mountmmc='doas /home/igor/arch/scripts/mount.sh mmc'

usb() {
    doas '/home/igor/arch/scripts/umount.sh' /mnt/*
}

umountall() {
    doas '/home/igor/arch/scripts/umount.sh' /mnt/* /home/igor/_*
}

alias lsblk='lsblk -o NAME,UUID,FSTYPE,SCHED,RM,SIZE,TYPE,MOUNTPOINTS'
alias ddiff='code --diff'
alias wget='wget --no-hsts'
alias ytdlhq='yt-dlp -f "bestaudio/best" -o "%(title)s.%(ext)s" -v --extract-audio --audio-quality 0 --audio-format mp3 '
alias ytdl='/home/igor/arch/scripts/ytdl.sh'
#alias firefox='firefox-socket'
alias ncdu='ncdu --color dark'
alias myip='curl https://avacyn.radiance.hr/ip'
alias srcinfo='makepkg --printsrcinfo > .SRCINFO'
alias df2='dysk'
alias df3='duf'
alias dmesg='doas dmesg'
alias locate='locate --ignore-case'
alias picam='/home/igor/git/hid/scripts/client.sh'
alias vboxload='doas modprobe -a vboxdrv vboxnetadp vboxnetflt'

# shellcheck disable=SC1090
_source() {
    [ -f "${1}" ] && source "${1}"
}

# user-dirs.dirs target
if [ ! -d '/tmp/xdg-dirs/' ]
then
    mkdir -p '/tmp/xdg-dirs/'
    chmod 700 '/tmp/xdg-dirs/'
fi

_source '/home/igor/arch/scripts/env.sh'
_source '/usr/share/git/completion/git-prompt.sh'
_source '/home/igor/arch/lf/icons.sh'

# server aliases
_source '/home/igor/git/radiance/ssh/aliases.sh'
_source '/home/igor/git/pi/tunnels/aliases.sh'

_gray="\[\033[0;37m\]"
_reset="\[\033[0m\]"
_green_b="\[\033[1;32m\]"

PS1="\w \$(__git_ps1 \"${_gray}(%s)${_reset} \")${_green_b}>>${_reset} "
