#!/bin/sh

#mv -v "/usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay" "/usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay-backup"

/usr/bin/apulse /usr/share/teams/teams "$@" --disable-namespace-sandbox --disable-setuid-sandbox