#!/bin/bash
# shellcheck disable=SC2181,SC2115

alias ls='LC_COLLATE=C ls -A -o -h --color=always --group-directories-first'

alias chx='chmod +x'
alias permof='stat --printf "%a\n"'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'
alias sudo='doas'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec sx'

fixntp() {
    doas rc stop ntpd
    doas ntpd -gq
    doas rc start ntpd
}

alias reboot='doas /home/igor/arch/scripts/reboot.sh reboot'
alias poweroff='doas /home/igor/arch/scripts/reboot.sh poweroff'

alias rsnc='doas pacman -Rsnc'
alias work='/home/igor/arch/scripts/work.sh'
alias speedtest='wget http://mirror.carnet.hr/debian-cd/10.10.0/amd64/iso-cd/debian-10.10.0-amd64-netinst.iso -O /dev/null'
alias syu='doas pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
alias mountdisk='doas mount -t ext4 -U 9989d2cc-d8bd-4919-a8ca-2395b60969b8 /home/igor/_disk'
alias mountmmc='doas mount -t ext4 -U ce63484b-3828-4024-9f9c-c120f43ca4ec /home/igor/_mmc'
alias mountazure='/home/igor/arch/scripts/azure.sh'
alias ddiff='code -d'
alias wget='wget --no-hsts'
alias rezije='node /home/igor/git/rezije/main.js'
alias ytdl='youtube-dl --extract-audio --audio-format mp3 '
alias firefox='firefox-socket-control'
alias ncdu='ncdu --color dark'

usb() {
    for _f in /mnt/*
    do
        if [ "${_f}" != "/mnt/*" ]
        then
            fuser -Mk "${_f}"
            doas umount -qv "${_f}"
            rm -vrf "${_f}"
        fi
    done
}

alias vboxload='doas modprobe -a vboxdrv vboxnetadp vboxnetflt'
#alias watchincrease='sudo sysctl fs.inotify.max_user_watches=524288'

source '/home/igor/arch/scripts/env.sh'
source '/usr/share/git/completion/git-prompt.sh'
source '/home/igor/arch/lf/icons.sh'

_bold=$(tput bold)
_green=$(tput setaf 2)
_gray=$(tput setaf 7)
_reset=$(tput sgr0)
PS1='\w $(__git_ps1 "\[${_gray}\](%s)\[${_reset}\] ")\[${_green}\]\[${_bold}\]>>\[${_reset}\] '
