#!/bin/bash
# shellcheck disable=SC2181,SC2115

alias ls='LC_COLLATE=C ls -A -o -h --color=always --group-directories-first'

alias chx='chmod +x'
alias permof='stat --printf "%a\n"'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'
alias sudo='doas'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec sx'

work() {
    local -a array=()
    mapfile -t array < <( jq -crM '.work | "/d:" + .domain, "/v:" + .host, "/u:" + .user, "/p:" + .password' "${HOME}/arch/secret.json" )
    echo "Connecting to: ${array[0]} ${array[1]} ${array[2]}"
    xfreerdp /cert-ignore /bpp:32 /network:lan /audio-mode:2 /multimon /floatbar:sticky:off /gfx:RFX -themes -wallpaper "${array[@]}"
    echo "Disconnected"
}

rsnc() {
    doas pacman -Rsnc "$@"
    echo -e "\033[32mUpdating db...\033[0m"
    doas updatedb
    echo -e "\033[31mCheck for remaining files in ${HOME}\033[0m"
}

fixntp() {
    doas rc stop ntpd
    doas ntpd -gq
    doas rc start ntpd
}

todo() {
    if [ "${1}" = "off" ] || [ -z "${1}" ]
    then
        if [ -z "${1}" ]
        then
            qtextpad "${HOME}/.todo" 
        fi
        local -r pid="$(pgrep -f conkyrc-todo)"
        if [ -n "${pid}" ]
        then
            echo "Killing existing conky instance (${pid})"
            /usr/bin/kill --verbose --signal TERM --timeout 10000 KILL "${pid}"
        fi
        if [ -z "${1}" ]
        then
            conky -d -c "${HOME}/arch/conky/conkyrc-todo" --xinerama-head 0 > /dev/null 2>&1
        fi
    else
        echo "invalid parameter"
    fi
}

reboot() {
    /home/igor/arch/scripts/reboot.sh
    doas /usr/bin/reboot
}

poweroff() {
    /home/igor/arch/scripts/reboot.sh
    doas /usr/bin/poweroff
}

alias speedtest='wget http://mirror.carnet.hr/debian-cd/10.10.0/amd64/iso-cd/debian-10.10.0-amd64-netinst.iso -O /dev/null'
alias syu='doas pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
#alias mountdisk2='doas mount -t ext4 -U 23147c37-efb6-4837-83aa-87808c70b87a /home/igor/_disk2'
alias mountdisk='doas mount -t ext4 -U 9989d2cc-d8bd-4919-a8ca-2395b60969b8 /home/igor/_disk'
alias mountmmc='doas mount -U ce63484b-3828-4024-9f9c-c120f43ca4ec /home/igor/_mmc/'
alias mountazure='/home/igor/arch/scripts/azure.sh'
alias ddiff='code -d'
alias wget='wget --no-hsts'
alias rezije='node /home/igor/git/rezije/main.js'
alias ytdl='youtube-dl --extract-audio --audio-format mp3 '
alias firefox='firefox-socket-control'
alias ncdu='ncdu --color dark'

usb() {
    doas umount -v /mnt/* || echo "umount failed"
    rm -vrf /mnt/* || echo "rm failed"
}

alias vboxload='doas modprobe -a vboxdrv vboxnetadp vboxnetflt'
#alias watchincrease='sudo sysctl fs.inotify.max_user_watches=524288'

source '/home/igor/arch/scripts/env.sh'
source '/usr/share/git/completion/git-prompt.sh'
source '/home/igor/arch/misc/lf/icons.sh'

_bold=$(tput bold)
_green=$(tput setaf 2)
_gray=$(tput setaf 7)
_reset=$(tput sgr0)
PS1='\w $(__git_ps1 "\[${_gray}\](%s)\[${_reset}\] ")\[${_green}\]\[${_bold}\]>>\[${_reset}\] '
