#!/bin/bash
# shellcheck disable=SC2181

alias ls='LC_COLLATE=C ls -A -o -h --color=always --group-directories-first'

alias chx='chmod +x'
alias permof='stat --printf "%n - %a\n"'
alias sizeof='du -sh'
alias grep='grep --color'
alias c='clear'
alias x='exit'

alias sr='screen -r'
alias sn='screen -S'

alias startx='exec startx -- -logverbose 0 -nolisten tcp -nolisten unix'

work() {
    local -a array=()
    mapfile -t array < <( jq -crM '.work | "/d:" + .domain, "/v:" + .host, "/u:" + .user, "/p:" + .password' "${HOME}/arch/secret.json" )
    echo "Connecting to: ${array[0]} ${array[1]} ${array[2]}"
    xfreerdp /cert-ignore /bpp:32 /network:lan /audio-mode:2 /multimon /floatbar:sticky:off /gfx:RFX -themes -wallpaper "${array[@]}"
    echo "Disconnected"
}

rsnc() {
    sudo pacman -Rsnc "$@"
    echo -e "\033[32mUpdating db...\033[0m"
    sudo updatedb
    echo -e "\033[31mCheck for remaining files in ${HOME}\033[0m"
}

fixntp() {
    sudo rc stop ntpd
    sudo ntpd -gq
    sudo rc start ntpd
}

todo() {
    if [ "${1}" = "off" ] || [ -z "${1}" ]
    then
        if [ -z "${1}" ]
        then
            qtextpad "${HOME}/.todo" 
        fi
        local -r pid="$(pgrep -f conkyrc-todo)"
        if [ -n "${pid}" ]
        then
            echo "Killing existing conky instance (${pid})"
            /usr/bin/kill --verbose --signal TERM --timeout 10000 KILL "${pid}"
        fi
        if [ -z "${1}" ]
        then
            conky -d -c "${HOME}/arch/conky/conkyrc-todo" --xinerama-head 0 > /dev/null 2>&1
        fi
    else
        echo "invalid parameter"
    fi
}

alias speedtest='wget http://mirror.carnet.hr/debian-cd/7.8.0/amd64/iso-cd/debian-7.8.0-amd64-netinst.iso -O /dev/null'
alias syu='sudo pacman -Syu'
alias aur='auracle outdated'
alias fixres='/home/igor/arch/scripts/fixres.sh'
alias snd='/home/igor/arch/scripts/sound.sh'
alias mountdisk="sudo mount -t ext4 -U 23147c37-efb6-4837-83aa-87808c70b87a /home/igor/_disk/"
alias mountmmc="sudo mount -U ce63484b-3828-4024-9f9c-c120f43ca4ec /home/igor/_mmc/"
alias ddiff="code -d"
alias wget="wget --no-hsts"
alias rezije='node /home/igor/git/rezije/main.js'
alias ytdl='youtube-dl --extract-audio --audio-format mp3 '

mountlinode() {
    local -r public="/home/igor/_public/"
    local -r private="/home/igor/_private/"
    mkdir -p "${public}"
    mkdir -p "${private}"
    local -r username="$(jq -crM '.linode.samba.username' "${HOME}/arch/secret.json")"
    local -r password="$(jq -crM '.linode.samba.password' "${HOME}/arch/secret.json")"
    sudo mount -t cifs -o username="${username}",password="${password}",uid="$(id -u)",gid="$(id -g)" //avacyn.aerium.hr/public "${public}"
    sudo mount -t cifs -o username="${username}",password="${password}",uid="$(id -u)",gid="$(id -g)" //avacyn.aerium.hr/private "${private}"
}

unmountusb() {
    sudo umount -v /mnt/igor/* || echo "umount failed"
    rm -vrf /mnt/igor/* || echo "rm failed"
}

alias vboxload="sudo modprobe -a vboxdrv vboxnetadp vboxnetflt"
alias watchincrease='sudo sysctl fs.inotify.max_user_watches=524288'

source "/home/igor/arch/scripts/env.sh"

source /usr/share/git/completion/git-prompt.sh

bold=$(tput bold)
green=$(tput setaf 2)
gray=$(tput setaf 7)
reset=$(tput sgr0)
PS1='\w $(__git_ps1 "\[$gray\](%s)\[$reset\] ")\[$green\]\[$bold\]>>\[$reset\] '

