#!/bin/sh

rm -vrf "${HOME}/.nuget"
rm -vrf "${HOME}/.local/share/NuGet"
rm -vrf "${HOME}/.npm"
rm -vrf "${HOME}/.templateengine"
rm -vrf "${HOME}/.mozilla"
rm -vrf "${HOME}/.cmake-js"
rm -vrf "${HOME}/.nv"
rm -vrf "${HOME}/.dotnet"
rm -vrf "${HOME}/.aspnet"
rm -vrf "${HOME}/.password-store"
rm -vrf "${HOME}/.avidemux6"
rm -vrf "${HOME}/.putty"
rm -vrf "${HOME}/.sqlsecrets"
rm -vrf "${HOME}/.lesshst"
rm -vrf "${HOME}/.node_repl_history"
rm -vrf "${HOME}/.wget-hsts"
rm -vrf "${HOME}/.fltk"
rm -vrf "${HOME}/.pki"
rm -vrf "${HOME}/.omnisharp"
rm -vrf "${HOME}/.gnupg"