#!/bin/sh

_vnc() {

    # daemons
    xsettingsd -c "${HOME}/arch/xfce4-terminal/xsettingsd" &

    # bacgkround
    xsetroot -solid '#008080'

    # interface
    tint2 -c "${HOME}/arch/tint2/tint2rc-vnc" &
}

_desktop() {

    # xorg settings
    xset -display :0.0 dpms 0 0 0
    nvidia-settings -a [gpu:0]/GpuPowerMizerMode=1
    
    # alsa
    "${HOME}/arch/scripts/sound.sh" pch

    # daemons
    xsettingsd -c "${HOME}/arch/xfce4-terminal/xsettingsd" &
    #xcompmgr -a &

    # resolution and background
    "${HOME}/arch/scripts/fixres.sh"
    xwallpaper --stretch "${HOME}/arch/wall/default5.png"

    # conky kernel
    conky -q -d -c "${HOME}/arch/conky/conkyrc-kernel" --xinerama-head 0
    conky -q -d -c "${HOME}/arch/conky/conkyrc-kernel" --xinerama-head 1
    conky -q -d -c "${HOME}/arch/conky/conkyrc-kernel" --xinerama-head 2

    # conky tint2
    conky -q -d -c "${HOME}/arch/conky/conkyrc-tint2"

    # tray
    tint2 -c "${HOME}/arch/tint2/tint2rc-top" > /dev/null 2>&1 &
    tint2 -c "${HOME}/arch/tint2/tint2rc-bottom" > /dev/null 2>&1 &

    # other
    sleep 1
    "${HOME}/arch/scripts/clip.sh" > "${HOME}/clip.log" 2>&1 &
    #sleep 1
    #flameshot &
    #sleep 1
    #synergy &
}

if /usr/bin/xdpyinfo | grep VNC > /dev/null
then
    _vnc
else
    _desktop
fi
